### ISSUE TITLE
Project saving before import should be optional

### ISSUE THREAD

**Issue by czyzby** [raeleus/skin-composer#1]
Currently you cannot import an existing skin without saving the current project, even if it's empty. It would be great if you added another option to the dialog that would allow the user to skip project saving.

**Comment by raeleus** [comment]
The reason that the import process is as convoluted as it is now is to avoid accumulating a lot of files in the temp folder that will go unnoticed by the user. In retrospect, it would be trivial to just transfer these files to the save path when the user decides to save. This can be in the next version.

**Comment by raeleus** [comment]
I added this feature with my latest commit. I'll make a release version as soon as I fix some potential, unrelated bugs.
