### ISSUE TITLE
Crash when trying to open on linux

### ISSUE THREAD

**Issue by jcassani** [raeleus/skin-composer#10]
Hi, it was crashing with  

> java.lang.NoSuchMethodError: com.badlogic.gdx.scenes.scene2d.Stage.setKeyboardFocus(Lcom/badlogic/gdx/scenes/scene2d/Actor;)

I fixed updating VisUI to version 1.2.3

**Comment by raeleus** [comment]
Thanks! I haven't done much testing in Linux. I'll include that in the next release.

**Comment by raeleus** [comment]
I included the latest version of VisUI with the new version of Skin Composer.
