### ISSUE TITLE
Cannot click on and type in any textfields after live previewing in Scene Composer

### ISSUE THREAD

**Issue by Taraxanoid** [raeleus/skin-composer#105]
I have created a simple scene in Scene Composer with a textfield in a cell. It seems the first time I live preview this (after starting the software and loading the project file) everything works fine and I can click in and type in textfields on the live preview and elsewhere in Skin/Scene Composer. However after going into edit on the table and then live previewing again, I can't click on or type in any textfield, including both the live preview fields and even fields in the Scene and Skin Composer UI. I have to close the program and re-open to get this functionality back.

Even using tab to try and get focus in text fields doesn't work, and cannot type in them. This issue also happens with other projects I have tried and the Plain James UI sample project.

I have tried multiple versions of Skin Composer, from 45 going back to version 40, same issue occurs. I am sure I did not have this issue previously when I first made my project (which would have been with version 42 or 43 initially). I did update Windows recently however...

I'm running Windows 10 Home version 10.0.19043 build 19043 x64 based PC. My installed JRE version is 1.8.0_301. I also tested on JRE 11 to see if that would fix the issue but alas no.

Edit: just wanted to add that a friend of mine who is running Linux (ubuntu 20.04) also tested this and did not experience this issue/bug.

**Comment by raeleus** [comment]
I'm sorry, I've been trying to reproduce this issue and I can't manage it. I'll leave it open for now if I stumble on it later. Sorry!
