### ISSUE TITLE
FreeType Font generator glitch

### ISSUE THREAD

**Issue by CrisN4N** [raeleus/skin-composer#107]
I use Skin Composer the latest version.
If i use fonts (ttf) with FreeTypeFontGenerator (with custom json loader) i haven't any problem.
Font view:
![изображение](https://user-images.githubusercontent.com/89037905/130323885-7937e77c-43b2-429c-9b13-bbf9a056a261.png)
Font settings:
![изображение](https://user-images.githubusercontent.com/89037905/130323908-84719ba0-b408-40b1-b28c-0e41f7beb320.png)

But i decided to generate same (fnt) font.
Used identical settings:
![изображение](https://user-images.githubusercontent.com/89037905/130324023-8f7c458d-0992-47e4-ad3a-8f6e6a9a5ec9.png)
And got: 
![изображение](https://user-images.githubusercontent.com/89037905/130324096-0e949ac3-735f-44a8-b85b-13f1664f64a3.png)

Comparison
(with FreeTypeFontGenerator)
![изображение](https://user-images.githubusercontent.com/89037905/130324140-f71d807a-6a5e-41e4-90aa-c73be6447319.png)
(generated fnt)
![изображение](https://user-images.githubusercontent.com/89037905/130324146-a1cb6baa-a025-4da0-a33a-f1f0509a59a1.png)

So... As you can see, the font clarity drops.
How i can fix it? (i am sure that it is my blame, but i can't find solution - i tried to change different settings in fnt generator)

**Comment by raeleus** [comment]
That's an interesting observation. I'll look at it when I have time. Thank you for pointing it out.

**Comment by raeleus** [comment]
It seems you have some odd system settings that are causing the entire UI to be blurry and rounding pixels incorrectly. Are you using some sort of window manager or a weird OS? I'm going to close this for now.
