### ISSUE TITLE
NinePatch drawable preview glitch

### ISSUE THREAD

**Issue by CrisN4N** [raeleus/skin-composer#108]
I want to create ProgressBar skin. 
I create background drawable for it using 9 patch.
After loading simple image and setting padding and content i got:
![изображение](https://user-images.githubusercontent.com/89037905/130356856-3e112756-fb12-4cd7-8c67-c2cc171067e5.png)
I tried to change preview actor size, but this glitch still alive.
As you can see, the border lines are more bold and the right side are white instead black.
(preview in creation window is broken)

After saving THIS 9 patch (with THIS settings), i can see:
![изображение](https://user-images.githubusercontent.com/89037905/130356902-27ac1a8b-ebfb-4157-98b1-eb8af82f391d.png)
(preview in progressbar skin is normal)

Image for testing:
![ProgressbarBgrTest](https://user-images.githubusercontent.com/89037905/130357007-be4e50f6-0576-4d51-916e-7fa81330f2c1.png)

Skin Composer ver 45

**Comment by raeleus** [comment]
It seems you have some odd system settings that are causing the entire UI to be blurry and rounding pixels incorrectly. Are you using some sort of window manager or a weird OS? What are your texture packer settings for preview (you can find a link in settings). I'm going to close this for now.

**Comment by CrisN4N** [comment]
@raeleus maybe you are right. I use win 7, but it is virtual machine (vurtual box with directx support)

**Comment by CrisN4N** [comment]
@raeleus  i will try to use skin composer in host system later
