### ISSUE TITLE
xprop: command not found

### ISSUE THREAD

**Issue by mttkay** [raeleus/skin-composer#117]
It looks like Skin Composer shells out to `xprop` on Linux when opening a file chooser.

```shell
[19:15:53] ~ java -jar bin/skin-composer-linux/lib/app/SkinComposer.jar 
sh: line 1: xprop: command not found
```

I'm on Fedora 35, and xprop was not installed. I suspect because it's an X11 tool, and Fedora ships Wayland by default, which the wider Linux community is starting to adopt.

The issue is fixable by installing xprop, e.g.:

```shell
sudo dnf install xprop
```

This should probably be pointed out in the installation instructions, or perhaps not be relied on going forward.

**Comment by raeleus** [comment]
I use TinyFileDialogs for those dialogs. I'll test the alternative available in LWJGL. It that doesn't work, I'll just put up a disclaimer. Thanks.

**Comment by mttkay** [comment]
Appreciate it, thanks!
