### ISSUE TITLE
Wrong java code generated by SplitPane in scene composer

### ISSUE THREAD

**Issue by LyricSeraph** [raeleus/skin-composer#118]
Version: 46

Code generated with SplitPane will duplicate the first pane part twice and miss the second pane.

See example below:

UI display on scene composer:
<img width="1187" alt="QQ20220219-191408@2x" src="https://user-images.githubusercontent.com/6013519/154798607-e947b137-ab1c-4662-bee4-a27a94cacb72.png">

Code generated:

```Java
// impots...
public class Core extends ApplicationAdapter {
    private Skin skin;

    private Stage stage;

    public void create() {
        stage = new Stage(new ScreenViewport());
        skin = new Skin(Gdx.files.internal("skin.json"));
        Gdx.input.setInputProcessor(stage);

        Table table = new Table();
        table.setFillParent(true);


        Label label = new Label("first pane", skin);

        label = new Label("first pane", skin);
        SplitPane splitPane = new SplitPane(label, label, false, skin);
        table.add(splitPane);
        stage.addActor(table);
    }

    // remaining codes
}
```

**Comment by LyricSeraph** [comment]
It looks the wrong pane is passed on this line:

https://github.com/raeleus/skin-composer/blob/33e33c97385009eadc99b5de609a3347c0208897/core/src/com/ray3k/skincomposer/dialog/scenecomposer/DialogSceneComposerJavaBuilder.java#L937

**Comment by raeleus** [comment]
Oh my! What a big screw up. I'll make an update soon. Thanks for your research on this.
