### ISSUE TITLE
Window placed in the wrong position when I open it

### ISSUE THREAD

**Issue by kz-n** [raeleus/skin-composer#119]
https://user-images.githubusercontent.com/64893077/157598203-fcf87e8e-58f9-4df8-a919-f65bfc0eb6cd.mp4

I use two monitors one with a smaller resolution than the other and can't really use this, It always opens in the other monitor at a way to big size for me to move it, and even if i try to stretch it to my other screen, i still can't drag it to a reasonable position.

I use Xfce4 with EndeavourOS

**Comment by kz-n** [comment]
Main screen (showed on screen) 1920x1080, Second screen (where skin composer opens) 1366x768

**Comment by kz-n** [comment]
If I click and hold the window while it's starting this doesn't happen

**Comment by raeleus** [comment]
That's a good work around, but I'll have a aolution aoon. Sorry!

**Comment by raeleus** [comment]
This will be resolved with the next update. Thanks!
