### ISSUE TITLE
Minor issues DialogSceneComposerJavaBuilder

### ISSUE THREAD

**Issue by deviodesign** [raeleus/skin-composer#135]
I found a few small mistakes when exporting with scene composer.
Using: LibGDX version 1.11.0

#### Fixes:
- [x] Duplicate .setTouchable gets added if actor.touchable != Touchable.childrenOnly and actor.visible is false.
- [x] ``.setTouchable`` gets passed a boolean a few times (e.g. [line 110](https://github.com/raeleus/skin-composer/blob/694111ce6eb1876df884dfba2f50ad8eb6c2c059/core/src/com/ray3k/skincomposer/dialog/scenecomposer/DialogSceneComposerJavaBuilder.java#L110)) but requires Touchable type
- [x] ``.preferredSize`` should be ``.prefSize``
- [x] ``.preferredWidth`` should be ``.prefWidth``
- [x] ``.preferredHeight`` should be ``.prefHeight``
- [x] ``.setPreferredRows`` should be ``.setPrefRows``
- [x] ``.setSplit`` should be ``.setSplitAmount``
- [x] ``.align`` should be ``.rowAlign`` on [Line 824](https://github.com/raeleus/skin-composer/blob/694111ce6eb1876df884dfba2f50ad8eb6c2c059/core/src/com/ray3k/skincomposer/dialog/scenecomposer/DialogSceneComposerJavaBuilder.java#L824)
- [x] ``.align`` should be ``.columnAlign`` on [Line 1069](https://github.com/raeleus/skin-composer/blob/694111ce6eb1876df884dfba2f50ad8eb6c2c059/core/src/com/ray3k/skincomposer/dialog/scenecomposer/DialogSceneComposerJavaBuilder.java#L1069)
- [x] ``.setScrollBarsVisible`` should be ``.setScrollbarsVisible``
- [x] ``.setName``'s param should have quotation marks on SimTable
- [x] ``.fillX`` and ``.fillY`` shouldn't have boolean params

Note: LibGDX itself has some inconsistent naming.
- fadeScrollBars
- setScrollbarsVisible
- setScrollBarTouch

**Comment by raeleus** [comment]
Those are great finds! I'll work on those soon.

**Comment by raeleus** [comment]
That would be great. I have a full load right now. Thanks.
