### ISSUE TITLE
Use skin-composer with visui

### ISSUE THREAD

**Issue by felixvolz** [raeleus/skin-composer#14]
I'm interested in using skin-composer with [https://github.com/kotcrab/vis-editor/wiki/VisUI](VisUI)

Skin-composer cant read/write VisUI componetns (i.e. VisTextButton etc) to/from json

Can this feature be added? 

p.s. just started using your tool and its very handy!

**Comment by raeleus** [comment]
I'm working on it. It's going to take a while before that feature is ready. Thanks for your feedback!

**Comment by raeleus** [comment]
You can do this with version 8 now,  however a more direct VisUI template would make this much easier. Stay tuned for that update.

**Comment by raeleus** [comment]
A template for VisUI has been implemented with the Welcome screen in version 10.
