### ISSUE TITLE
Weird behaviour when importing a skin with very small "bordered" drawables.

### ISSUE THREAD

**Issue by LennartH** [raeleus/skin-composer#15]
I want to change the font of the skin [tixel](https://github.com/kotcrab/vis-ui-contrib/tree/master/skins/tixel). So I imported the skin, after removing all VisUI components and adding `{file: droid-sans-13.fnt }` to `small-font`. Everything seemed fine, but the ScrollPanes background wasn't just a 1px border. Somehow it has become a radial flow.
The reason could be, that the used drawable is very small (5x5, where the actual information is stored in the inner 3x3).

**Edit:** Yes, the very small drawable caused the behavior. After Resizing the corresponding png to 10x10 is the problem gone.
**Edit 2:** No it's still a problem. It looks fine inside Skin Composer, but it's still broken, after exporting the skin and using it in the game.

**Comment by raeleus** [comment]
Importing skins from the wild is a tricky matter. I'll take a look at it when I get back today. Thanks for the report!

**Comment by LennartH** [comment]
Yep, I didn't expect it to work with the first try.

But I can now confirm, that the Skin Composer causes the skin to break. I packed the raw data of the skin  (with a different font) using libgdx' Texture Packer, replaced the .fnt and the .atlas/.png and changed the .json, so that the new font is used and it worked.

**Comment by raeleus** [comment]
Sorry, it took me awhile to get to a computer today. I was able to reproduce the issue. It's not necessarily Skin Composer's fault. Open the .atlas exported by skin composer and change the filter value to "Nearest,Nearest". The original skin has this value. Apparently, when LibGDX renders small images stretched over an area like this under "Linear,Linear" you get the gradient effect.

Now, the real issue at hand is that Skin Composer has these texture atlas settings hardcoded into the program. You'll have to manually change it in your exports If you want to do this sort of operation regularly. I could expose these settings or provide a template file for editing. It's not something that most skins would really need every time though. I'll consider it in the future.

**Comment by LennartH** [comment]
Yes that did the trick. That's what you get if you just want to adjust something quickly, without reading the technical background. Thanks for the fast help.

A quick fix for this issue would be to use the feature to store the settings of the Texture Packer in a "pack.json" (see [Documentation](https://github.com/libgdx/libgdx/wiki/Texture-packer#configuration)). This way everyone could specify how the skins data should be packed and you don't have to implement an UI to configure the settings.

**Comment by raeleus** [comment]
I didn't realize it would be that easy.  I'll add it for the next version.
