### ISSUE TITLE
jpackage download link broken

### ISSUE THREAD

**Issue by upost** [raeleus/skin-composer#151]
Here:
https://github.com/raeleus/skin-composer/wiki/libGDX-and-JPackage

Please update the docs with a ready-to-use example. This would be very kind, thank you!

**Comment by raeleus** [comment]
I updated the link. I'm not going to update any changes to the examples though. Instead, I will redirect people to use GDX Liftoff which already has done the hard work. Thanks for bringing this to my attention.
