### ISSUE TITLE
Version 8 code cannot run

### ISSUE THREAD

**Issue by hermangh** [raeleus/skin-composer#16]
I've downloaded the version 8 source code and put it into Android Studio. I've followed the instructions from read.me to make necessary settings or actions. When executing the DesktopLauncher, I received error as below:

com.badlogic.gdx.utils.SerializationException: Error reading file: skin-composer-ui/skin-composer-ui.json

The mentioned json file is located under the core/assets folder. Should I copied the skin-composer-ui to other location? Please advise. Thanks.

**Comment by raeleus** [comment]
The file is in the correct location. I don't use Android Studio to know, but I believe you have to set the working directory to "<some path>/core/assets/". That would be in the menu Run >> Edit Configurations.

**Comment by hermangh** [comment]
Setting the working directory works. Thanks.

However, just like my another post on the .jar file, I cannot import any skin .json file. The 'Choose' button just not enabled. Please advise. Thanks.

**Comment by raeleus** [comment]
See the other issue I just replied to. Thank you so much for your patience in this matter.
