### ISSUE TITLE
Unable to go back to splash screen

### ISSUE THREAD

**Issue by czyzby** [raeleus/skin-composer#18]
Since splash screen offers the option to create new projects using specific templates, it would be nice if you could go back to it - or at least access the new templates through the menu. After a quick look at the UI, I have found no such options.

**Comment by raeleus** [comment]
I stuck it in project>settings. However,  it would be better served to be in the file menu. Thanks for the feedback.

**Comment by czyzby** [comment]
To be honest, I wouldn't even look for the splash screen in the _project_ settings. Putting it in the file submenu seems like a better UX design.

**Comment by raeleus** [comment]
This is in 10A. Thank you.
