### ISSUE TITLE
Feature Request: low and high resolution skins

### ISSUE THREAD

**Issue by RaimundWege** [raeleus/skin-composer#19]
As an user I want to manage only one skin but support different screen sizes. The following problem occurs when the skin is used on an old smartphone and a new one with retina display at the same time: On the old smartphone everything looks like expected but on the new one with retina everything is tiny (or pixelated in case of a stretched-viewport).

Possible approach:
- each drawable can have more than one image (one image for each size-class).
- each size-class generates an own skin (my app will choose the right skin on startup).
- if an image for a size-class is missing: fallback to the image of an existing size-class.

For example a simple button could have the following size-classes:
- button.png (default size-class)
- button@2x.png (retina size-class / scaled with factor 2)

If I want to add a button for those size-classes I drag'n'drop those two images (button.png and button@2x.png) into the skin-composer and the skin-composer adds only one "button" drawable but saves both images. Later when I export this skin the skin-composer will generate two skins: 
- skin.json/skin.png and
- skin@2x.json/skin@2x.png

The same should be possible for fonts.

(this size-class and "@2x"-thingy is the way how apple solves this problem)

**Comment by raeleus** [comment]
I've been using separate skins to manage my normal and scaled versions. This is simple, but of course leads to a lot of duplicated work. Your proposed solution might be viable, however it will make the interface more complicated and will also take some time to code. I'll consider this for a future version.

**Comment by raeleus** [comment]
I've considered this and decided to not implement it. I'd recommend using an external texture packer to manage your low res and high res images separately. With a little copy-paste you can have both versions with the same skin file. Sorry!
