### ISSUE TITLE
GUI changes

### ISSUE THREAD

**Issue by czyzby** [raeleus/skin-composer#2]
- [x] Dialogs use stage background without any alpha applied, hiding everything beneath them. You could easily change the alpha value of stage background drawables to simply darken the stage under dialogs instead of completely hiding it. This looks especially awkward when you open the "about" dialog.
- [x] VisUI `FileChooser` uses default style, which does not exactly fit the current themes. You could add `FileChooserStyle` to your skin and use `VisUI.load(Skin)` method to replace the default VisUI skin with one of your own. It also features no stage background as opposed to other dialogs.
- [x] Image buttons have different sizes. Open `List` style for example to see what I mean. I think the font, color and drawable icons should have the same size (and its height could match the text field).
- [x] There is no application icon.

**Comment by raeleus** [comment]
Redesigned UI, switched to TinyFileDialogs, added application icon.

**Comment by czyzby** [comment]
Current UI could still use some love. If you want a modern editor look, I'd start with VisUI skin (which is really decent for game dev tools) and go from there, recoloring and changing widgets you don't like in particular. In [vis-ui-contrib](https://github.com/kotcrab/vis-ui-contrib) there's a recolorable VisUI skin (Tinted) which I made a while back, you could try that out.

**Comment by raeleus** [comment]
Truth be told, I don't like the look of VisUI skin or its current derivatives. I'm satisfied with Skin Composer's current look and functionality. I'm not going to spend a lot of time creating a new skin and adapting my widgets to have it ultimately look the same in the end. I'm still working toward making Skin Composer compatible with VisUI skins. One step at a time I'm afraid.

**Comment by czyzby** [comment]
Well, VisUI derivatives tend to look somewhat similar to modern IDE skins (IntelliJ, Visual Studio Code and so on), but I can see what you mean.
