### ISSUE TITLE
font image size bigger or equal than 1024x1024 

### ISSUE THREAD

**Issue by yosigosi** [raeleus/skin-composer#21]
I changed texture packer settings:
{
...
    maxWidth: 4096,
    maxHeight: 4096,
...
}
and it works as expected.
But, when I insert a font with a image size of 1024x1024, it says that the image size must be less than 1024x1024.
Once the maxWidth and  maxHeight parameters are 4096 it is supposed that  It must be allowed a font size of 1024x1024.

**Comment by raeleus** [comment]
The fix will be in the next release. The dialog was reading the wrong file for the preferences.

One question though: why such a huge font image? You should consider trimming any white space or use a different software that packs your font properly.

Thanks for letting me know about this issue.
