### ISSUE TITLE
Portability problem in .scmp

### ISSUE THREAD

**Issue by MartensCedric** [raeleus/skin-composer#22]
Since it saves the full path to the directory ex C:/$USER/Documents/MyProject/MySkins/myskin.scmp this causes loading crash if the path changes. For example I just cloned my project on Linux so I get something like /home/$USER/Documents/MyProject/MySkins/myskin.scmp and it obviously crashes since the other path does not find the files.
 
I would prompt the user to choose the new location of the file if it is missing.

**Comment by raeleus** [comment]
For projects that you plan on cloning, you should activate relative resources: Settings >> Keep resources relative. The assets you use will be copied to a data folder next to your SCMP file. Any changes or new assets should be placed in this folder. This will make your project portable.

However, I'll add a series of dialogs to address the missing files like you suggested. It shouldn't be to difficult. Thanks for the feedback.

**Comment by MartensCedric** [comment]
Thanks I did not see that! But yeah I think it would still need some error management, since I had to go in my .scmp file change the path manually

**Comment by raeleus** [comment]
This feature has been included in the newest version. Please review this and let me know if there are any additional issues.
