### ISSUE TITLE
Large fonts exportation is not done properly

### ISSUE THREAD

**Issue by MartensCedric** [raeleus/skin-composer#24]
When I export my skin with a large font (70 VCR Mono), LibGDX will not be able to parse my skin, unless I go in Hiero and export a 70 VCR Mono myself with a large background (2048x2048) and replace what Skin Composer exported. When I import my font into Skin Composer, there is no problem, it will read correctly. However, it does not export it in a way LibGDX can read it after.

This seems to be causes because the file vcr70.fnt has these lines : 

page id=0 file="vcr701.png"
page id=1 file="vcr702.png"
scaleW=512 scaleH=512 pages=2

When I actually have 1 file called vcr.png that's 2048x2048

**Comment by raeleus** [comment]
2048x2048 seems excessively large for a font. You should generate a font without any white space. You can do this with [Littera](http://kvazars.com/littera/) for example. Skin composer just copies and pastes the FNT file and embeds the PNG into the texture atlas. Please post your original FNT and PNG files. I'll see what I can do then. Thank you.
