### ISSUE TITLE
Fonts can't use special characters

### ISSUE THREAD

**Issue by ciberchico420** [raeleus/skin-composer#25]
Hello! first let me say that skin-composer is so great! Thank you so much for creating it.
I'm a spanish speaker developer and my games have to use a special character in spanish but skin-composer can't manage to do that. I just post this in case that the developer didn't know this is a issue and is willing to fix it, but if not i'll try to make it work for my own when i have some free time.

**Comment by raeleus** [comment]
I'm willing to work on that. Can you list the characters you think will be most useful to you and other Spanish speakers?

**Comment by ciberchico420** [comment]
For sure, the missing ones are: ñ, ¿, ¡, á, é, í, ó, ú, ü.
Thank you! you should put some kind of button to donate you some money!!

**Comment by raeleus** [comment]
I'll get that implemented soon. It shouldn't be too difficult unless there's some unforseen issue. Thanks for your kind words.

**Comment by raeleus** [comment]
Alright, it looks like I got it to work with version 14. Please note that you probably can't use font files named with the specified characters because of the way BitmapFont is written in LibGDX. Everything else should work with your proposed suggestion.
