### ISSUE TITLE
Illegal JSON format

### ISSUE THREAD

**Issue by cshiel** [raeleus/skin-composer#26]
The exported JSON does not have proper formatting and is invalid. The key MUST be surrounded by quotes as per the spec.

**Comment by raeleus** [comment]
You should take that up with the LibGDX folks. Accordingto the wiki: "It also supports a "minimal" format (the default), where both object property names and values are only quoted when needed." All the samples I've  seen use the minimal format. I can add an option to enable strict JSON, however it's not necessary for normal work.

**Comment by cshiel** [comment]
The library I use requires quotes. If possible please add an option to configure the Json formatting.

**Comment by raeleus** [comment]
This was a simple addition to version 15, however I was sick and very busy with work. Sorry it took so long.
