### ISSUE TITLE
Feature Request: Add a Hex field in the Color Picker

### ISSUE THREAD

**Issue by Tibi** [raeleus/skin-composer#28]
Hi,

It would be very useful to be able to copy & paste colors to & from Krita or Inkscape into the color picker.
Something like this.
![image](https://user-images.githubusercontent.com/50194/37094651-ca6cc84a-2213-11e8-9937-2db3624b31af.png)

What do you think?
If you like the idea and are not working on the color picker at the moment, I can try to implement this.

**Comment by raeleus** [comment]
It should be pretty easy to add. I'll have it in the next version. Thanks for the suggestion.

**Comment by raeleus** [comment]
It's in the dev branch now. It could probably use some testing before I roll it out though. Thanks again for your contribution.

**Comment by Tibi** [comment]
It seems to work quite nicely, I'm missing the alpha though.

**Comment by raeleus** [comment]
Whoops! I'm used to graphics programs defining RRGGBB only. It will now allow for RRGGBBAA as well.

**Comment by Tibi** [comment]
Thanks a lot!

It's not new but here is a small bug while you're at it:  when first opening the color of the alpha slider is wrong:
![image](https://user-images.githubusercontent.com/50194/37214577-bbc9f1e8-23b5-11e8-83d1-7db34bebe3a4.png)

No big deal, as soon as you move anything it switches back to the correct color.

**Comment by Tibi** [comment]
Also, when you edit in the # field, the alpha slider is not updated:

![image](https://user-images.githubusercontent.com/50194/37214815-737aaf58-23b6-11e8-80aa-de1d7e62f915.png)

**Comment by raeleus** [comment]
Fixed in dev. Thanks once again for your excellent observations.

**Comment by Tibi** [comment]
Well, I haven't done much, thanks to you for creating Skin Composer, it helps me keep my sanity when working with libGDX.

I can't properly test now, but I will tomorrow.

**Comment by raeleus** [comment]
I've made another skin to test the new version, and everything seems to be in order. However, I'm probably blind to any other bugs from working with the code for so long.
