### ISSUE TITLE
Keyboard shortcuts are using Qwerty instead of the local keyboard

### ISSUE THREAD

**Issue by Tibi** [raeleus/skin-composer#29]
Hi,

I'm using a funny keyboard layout on Windows 10, and to hit Ctrl+S I have to find the key where the S is on a qwerty keyboard.
Strange, as I have no such problem with other libGDX based apps on this PC.

**Comment by raeleus** [comment]
A strange problem indeed. I'll have to do some research. I recall someone having issues with their keyboard layout sometime back.

**Comment by Tibi** [comment]
It seems to be related to the LWJGL 3 backend, search for azerty in the following issue:
https://github.com/libgdx/libgdx/issues/3673

**Comment by raeleus** [comment]
It wasn't pretty, but I found a solution on the dev branch. I'll have it included with the next version. Thank you for helping out.

**Comment by Tibi** [comment]
Yep, it works for me!
