### ISSUE TITLE
Support for custom actors

### ISSUE THREAD

**Issue by czyzby** [raeleus/skin-composer#3]
Default Scene2D API is far from complete (otherwise projects like [VisUI](https://github.com/kotcrab/vis-editor/wiki/VisUI) would not exist), and most people usually end up creating some custom actors along the way. While Skin Composer would be somewhat useful, in most "serious" projects you would usually end up ending JSON files manually anyway. That's why I think there should be some kind of support for custom widgets.

When you think about it, you could easily allow the users for create custom styles without the source code or live previews. The user would have to enter the exact name of the style (for example, `com.github.czyzby.SomeWidget$SomeWidgetStyle`), and then choose the names and types of modifiable attributes - drawables, strings, fonts, colors, floats and booleans. As expected, there would be no live preview support, but at least you could specify the style within the GUI.

"Full" support of extra widgets would require some dynamic class loading, but it is certainly achievable. The user would have to choose the path to a source file containing the necessary stuff, and enter the names of actor and style classes - so they could be loaded with reflection. It does require some work, but I think it's worth it.

If you don't want to make it possible to customize additional actors, "hardcoded" VisUI support would be most welcome.

**Comment by raeleus** [comment]
I was dreading having to come up with live previews for custom classes, so thank you for coming up with a viable alternative. I do agree that Scene2D.ui is incomplete. Direct support for VisUI would be great, but I'd really have to get more familiar with that library first. This will be implemented in some fashion soon. Thanks for the great suggestion.

**Comment by raeleus** [comment]
This feature has been added with version 8. A direct sample/template for VisUI is forthcoming.
