### ISSUE TITLE
Allow fonts generated by FreeType

### ISSUE THREAD

**Issue by Wilwarin** [raeleus/skin-composer#31]
The default classes do not allow typing in a font name generated by FreeFont. With custom classes I can change the field to by of type text and type in the font I generate on runtime.

**Comment by raeleus** [comment]
Sounds like a good idea. Place holders in the font dialog might work for this. It's too bad you can't just generate TTF's in skins...

**Comment by Wilwarin** [comment]
Would be nice if LibGDX allowed TTF fonts. How would you approach adding the placeholder?

**Comment by raeleus** [comment]
I have this idea working in the drawables dialog right now. It would be like this: open fonts dialog, click freetype font, type in a name. This fake font can then be selected in any of the normal or custom styles. This would allow you to reference FreeType fonts (or any kind of font)  added manually in code.

**Comment by Wilwarin** [comment]
I've added a box in fonts dialog, it's adding the font with file as null, but that requires a lot of null checks everywhere and not exporting to skin file, as it will be added as a parameter. I'm in the process of changing the code, but maybe there's an easier way that I can't see :)

**Comment by raeleus** [comment]
Wow, you're able to understand my spaghetti code? Yeah, that's probably it. I haven't touched the font code in awhile. Thanks for your interest in finding a solution!

**Comment by Wilwarin** [comment]
Your program is very useful and I'd love to help as it will save many people lots of time, including me :) Damn, just noticed the drawables solution, that will be very helpful. ![My solution](https://user-images.githubusercontent.com/7014193/37490703-4ca259c6-2893-11e8-9488-f6dbc2e363b7.png) doesn't hold now!

**Comment by raeleus** [comment]
Just an FYI, I might have a pretty neat solution to this. It's just going to take some time to develop but you'll have Freetype Fonts closely integrated into Skin Composer. I haven't much time behind the keyboard, but my next week should be free and I can focus on this. I just didn't want you to spend too much of your time on this if I'm ultimately not going to use it. Thanks!

**Comment by Wilwarin** [comment]
Yeah I've added the fonts but I've got a few issues with the preview, font deletion, etc. You'll know where to look so I'll leave it for you :) Thank you!

**Comment by Wilwarin** [comment]
Hi raeleus,
Did you get a chance to look at that issue? Thanks :)

**Comment by raeleus** [comment]
I've been working on this diligently for the last week. I'm actually typing the last few touches as we speak. It amounts to two strategies: use basic placeholders and generate the fonts in code (recommended strategy) or generate the font in Skin Composer and use a custom serializer to load it in code. My Pen to the Paper UI sample show cases this in action: https://ray3k.wordpress.com/pen-to-the-paper-ui-skin-for-libgdx/

The serializer strategy is not very pretty, but is the only way I can do it without some serious changes to LibGDX classes. Anyway, you can see the latest in the Dev branch. Everything seems to be working and is ready for testing. I just need add some documentation and copy/paste option for the serializer code.

**Comment by Wilwarin** [comment]
I've looked at dev commits and I'm impressed. I'll test it today, see how it works :)

**Comment by raeleus** [comment]
This has been included with version 18. Let me know if you find any bugs. Thanks! Tutorial toward the end of the video here: https://www.youtube.com/watch?v=ImcS9jD-sXw&t=10s
