### ISSUE TITLE
Problem running skin composer in linux 32 bit

### ISSUE THREAD

**Issue by OtakuSenpai** [raeleus/skin-composer#34]
>java -jar Rss/skin_composer.jar 
>[LWJGL] Failed to load a library. Possible solutions:
>	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
>	b) Add the JAR that contains the shared library to the classpath.
>[LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
>[LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for >better diagnostics.
>Exception in thread "main" java.lang.UnsatisfiedLinkError: Failed to locate library: liblwjgl32.so
>	at org.lwjgl.system.Library.loadSystem(Library.java:146)
>	at org.lwjgl.system.Library.loadSystem(Library.java:66)
>	at org.lwjgl.system.Library.<clinit>(Library.java:49)
>	at org.lwjgl.system.MemoryUtil.<clinit>(MemoryUtil.java:60)
>	at org.lwjgl.system.MemoryStack.<init>(MemoryStack.java:60)
>	at org.lwjgl.system.MemoryStack.create(MemoryStack.java:79)
>	at org.lwjgl.system.MemoryStack.create(MemoryStack.java:70)
>	at java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:284)
>	at java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:180)
>	at java.lang.ThreadLocal.get(ThreadLocal.java:170)
>	at org.lwjgl.system.MemoryStack.stackGet(MemoryStack.java:605)
>	at org.lwjgl.system.MemoryStack.stackPush(MemoryStack.java:614)
>	at org.lwjgl.system.Callback.<clinit>(Callback.java:38)
>	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.initializeGlfw(Lwjgl3Application.java:78)
>	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:88)
>	at com.ray3k.skincomposer.desktop.DesktopLauncher.main(DesktopLauncher.java:54)

This is from running the version 18 and 19 of the app from a 32 bit machine on linux.
Hope you fix this issue.

**Comment by raeleus** [comment]
Thanks for posting. What distro are you running?

**Comment by raeleus** [comment]
Anyway, it seems to be an issue with LibGDX affecting all apps on the LWJGL3 backend running on Linux 32-bit. Hopefully this can be resolved soon. See https://github.com/libgdx/libgdx/issues/5186

**Comment by raeleus** [comment]
Turns out there is no LWJGL3 support for Linux 32-bit. I'm not going to revert back to LWJGL2, so that means your platform is no longer supported. I'm very sorry.
