### ISSUE TITLE
Feature Request: clear drawable property, ability to select none

### ISSUE THREAD

**Issue by NicEastvillage** [raeleus/skin-composer#36]
Currently when customizing a style's properties, it is not possible to remove a drawable. Say, for my ButtonStyle I choose a drawable for the property "checked". Later I regret that and want to remove it, but I can't.

I suggest one of the following:

1) Next to the drawable property, add a button, that when click clears the property.

2) When selecting a drawable, and the first drawable in the list will be a sqaure that says "None", and when choosing this, the property will be cleared.

Number 2 is probably easiest to implement. This feature would also be relevant for fonts or colors, but default color is white anyway.

**Comment by raeleus** [comment]
Hello. You can select "clear drawable" at the very bottom of the "Select a Drawable" dialog. This is very similar to your #2 suggestion. Admittedly, your idea is a little more user friendly, but I'm not willing to add it at this time. Thanks for the contribution.

**Comment by NicEastvillage** [comment]
My bad. Must have missed it or thought it cleared ALL drawables. Thanks!
