### ISSUE TITLE
execution error: Can’t make "F:/APP/ASSETS/assetsall" into type alias. (-1700)

### ISSUE THREAD

**Issue by agnel18** [raeleus/skin-composer#38]
Skin Composer is Awesome!
I opened it using the the command from my folder on a Mac -
java -jar -XstartOnFirstThread skin_composer_mac.jar

When I tried importing a project from another computer (Windows)
I got an error that the resources are missing.
When I clicked on the browse button to import.
I got this error on my Terminal:
20:109: execution error: Can’t make "F:/APP/ASSETS/assetsall" into type alias. (-1700)
I don't know what to do. Please help.
I'm exporting my files from the other PC for the time being.

**Comment by raeleus** [comment]
Thanks for your feedback!

The usual theme around here is that I don't have a Mac to test on, so I'm forced to guess in the interim. Try the following:

If you can, try making the project resources relative to the save file from the original PC: Project >> Settings >> Keep resources relative.

If that fails, export the project on the PC: File >> Export. Then try to import it on the Mac: File >> Import.

And finally, if all else fails, you can try editing the SCMP file manually. If you open the file in your favorite text editor, you'll see several lines referencing Windows file paths (most likely in the "drawables" section). You'll need to change these to the equivalent on your Mac drive.

None of these solutions are ideal. As far as preventing this error, I can hopefully find a way to catch it and throw up a missing file dialog. I'm not sure when I'll have the chance to that. Sorry!

**Comment by raeleus** [comment]
This will be resolved in the next version.
