### ISSUE TITLE
Example skins

### ISSUE THREAD

**Issue by czyzby** [raeleus/skin-composer#4]
It would be nice if you included a few example skins in the repository, so they could be loaded and modified. New LibGDX users could start with some solid GUI bases rather than from scratch.

**Comment by raeleus** [comment]
My intention was for folks to import the skins from the samples folder included with the releases. Currently SCMP files use absolute paths to images and don't port to other computers very well. Import gets around this. In the future I could revisit this with a nice pop up for new users with a choice of starter skins. We have Plain James and Star Soldier samples with more to come soon.

**Comment by raeleus** [comment]
This has been implemented with the Welcome screen in version 10.
