### ISSUE TITLE
Featue Request: 9-patch:  stretching down source png before creating 9-patch

### ISSUE THREAD

**Issue by Raduzz** [raeleus/skin-composer#43]
Hello,

I have a big png. I need to open it in 9-patch tool and set the paddings.
Then I need to stretch down the huge middle/stretchable area and then set the content borders.
And save is as 9-patch.

I also asked question here [stackoverflow scaling-raw-png-in-nine-patch-way](https://stackoverflow.com/questions/53161791/scaling-raw-png-in-nine-patch-way-before-saving-as-nine-patch-image)

**Comment by raeleus** [comment]
I suppose you're trying to scale down an image and also set NinePatch values for it. I think the best process for this is to scale down the image in a separate program and then bring it to Skin Composer. Photoshop and Gimp good tools for rescaling an image. If this is not what you're trying to do, please describe in more detail and provide examples. Thanks.

**Comment by Raduzz** [comment]
I want to scale down the image but the corners should keep the original size.
Original image: Left top corner is 40px wide, Right top corner is 40px wide. Middle area between the corners is 900px wide. This would be huge 9-patch. 

I want to have 40px(LeftTop) + 40px(RightTop) + 20px (middle).
If I scale it down the original image in Photoshop ten times then I have 4px(LeftTop) + 4px(RightTop) + 90px (middle). Rounded corners are destroyed.

**Comment by Raduzz** [comment]
:-) I have great respect for your work. But when I saw the video I just had to smile. It was far more complicated then thought. And my feature request makes even more sense now then before!

Imagine you have twenty images for your project and you do this (your video content) for all the images. Then an designer comes with graphic update and you must rework it all. Bullet into head.
Your guide wouldn't even work for my image which look similar to [vertical gradient](https://flyingmeat.com/acorn/docs/gradient_tool3.png).

EDITED: I see your preview scale does not work in the same way as in GDX texture packer. It would be more difficult for you to implement it,
Sorry for this I just run it once and when I wrote the lines bellow (Skin Composer was crashing when opening my project - i will report the issue)

I wold suggest solution for my request by Preview Image Save button.
Then what I will just have to do this:
1. Open "big.png" in yout 9-patch tool
2. Set the paddings
3. Make a preview small (10% vertical, 10% horizontal) (EDITED: Not as GDX Texture packer. It will not work.)
4. Save the preview as "small.png"
5. Open "small.png" instead of big.png
6. Set the same paddings  again ( I can live with it for now :-))
7. And save the result as small.9.png

There is many 9-patch editors with same functionality out there. But with this function your will be better and will bring you new users just because of these tool, even they don't use libgdx.
You will save users 80% of time.

**Comment by raeleus** [comment]
Sorry, I've been out sick. I'm still not going to add your suggestion,
sorry. The video I shown you was only to prove the concept. It can be done
much more efficiently with macros, etc. If I was using Illustrator, for
example, it would only be 3 actions. Ask you graphic designer to make the
image smaller. This is not what I want Skin Composer to do.
