### ISSUE TITLE
intergrating this with  my 2 rpg engine and removing  some usless textfields

### ISSUE THREAD

**Issue by macmanmatty** [raeleus/skin-composer#50]
do you mind if I integrate this with  the editor for my 2d RPG  engine? Also you may want to remove  the adding of drawables for certain things on  buttons and possible other scene 2d Classes  like focused or checked  as buttons don't have those fields and adding drawables for  them  will cause libGDX to crash.

**Comment by raeleus** [comment]
By all means, integrate Skin Composer as you see fit. Just make sure to credit me for my contributions.

About the new fields: these reflect new additions in LibGDX 1.9.9. If your editor needs to support older versions, feel free to make modifications. If you change the GDX version in Gradle, it should automatically populate the classes with the current fields. It will certainly break other things though. Good luck!
