### ISSUE TITLE
Feature Request: color as HEX in Export skin.json

### ISSUE THREAD

**Issue by ProZhar** [raeleus/skin-composer#51]
Hi.
It would be very useful to be able to add a checkpoint "Save Color as hex value" in the Export skin dialog.
Colors as hex are more compact and readable.

![default](https://user-images.githubusercontent.com/9317340/53967818-94925680-40fe-11e9-9523-00592400bb2b.png)

**Comment by raeleus** [comment]
Hey, I didn't know that was an option. I'll look at it ASAP

**Comment by ProZhar** [comment]
And maybe together would be able to add a checkpoint "Save Color as RGBA in one line " in the Export skin dialog too.
![aaaaaaaaaaaaaaaaa](https://user-images.githubusercontent.com/9317340/53968628-18990e00-4100-11e9-87ee-7becbc04b869.png)

**Comment by ProZhar** [comment]
Or add a radiobutton/togglebutton to switch between this two features :)

**Comment by raeleus** [comment]
I let libGDX's JSON implementation handle the heavy lifting for me. I'm not sure I have a say in how it's formatted.

**Comment by ProZhar** [comment]
> I let libGDX's JSON implementation handle the heavy lifting for me. I'm not sure I have a say in how it's formatted.

Understood

P.S. I just created issue to support your skin-composer ttf from ligdx-plugin :)
https://github.com/BlueBoxWare/LibGDXPlugin/issues/18

**Comment by raeleus** [comment]
This feature will be included in the next version. Thank you.
