### ISSUE TITLE
TextTooltipStyle style creates automatically after creating Label style

### ISSUE THREAD

**Issue by ProZhar** [raeleus/skin-composer#52]
Hi again.
Found some bug.
Steps:
0. Create an empty project.
1. Create some color that required for generating the ttf font.
2. Generate some ttf font for a label.
3. Choose class Label and only add a generated font to default style.
4. Save file and export skin.json.
5. Open skin.json in editor and see a created TextTooltipStyle that referrer to the default Label style. 

But we didn't create this style.

![zszs](https://user-images.githubusercontent.com/9317340/53973603-c0670980-4109-11e9-8838-2b7e27b1e2f9.png)

**Comment by raeleus** [comment]
I'm sorry to say that was intentional. The minimum requirement for a text tooltip is having a label style. Since default is available, it automatically populates it. I don't want to redo the way I handle this. Sorry!
