### ISSUE TITLE
neon-ui bug?

### ISSUE THREAD

**Issue by entangledloops** [raeleus/skin-composer#55]
I would have preferred to email or PM you, but I can't find any contact info anywhere on your app,  homepage (https://ray3k.wordpress.com), gamejolt, or youtube account. Maybe consider adding an email somewhere (unless you hid it intentionally)?

Anyway:
I noticed an odd thing about the neon-ui example. When I move my mouse slowly towards a Button or TextButton, the buttons highlight before my mouse is actually over them. It seems their bounds are larger than the actual displayed objects. When I export the example skin and load it up in libgdx, I get the same behavior. Meaning, the buttons feel too small, and they detect mouseover events before the mouse is visually over the component. Is this a bug or by design of the original author?

**Comment by raeleus** [comment]
Here is fine, I'm also on the libGDX Discord. The Neon UI skin uses a lot of glow around the edges so the image is larger than the border would have you think. If you really want to prevent that, you'd have to figure out how to modify the Button class to only register the mouse over after a small gap. No easy solution for that I'm afraid.
