### ISSUE TITLE
Ver. 29 creates JSON that libGDX can't load with 9 patches

### ISSUE THREAD

**Issue by phunni** [raeleus/skin-composer#56]
If I export a skin in ver. 29 that worked perfectly in ver. 28 libGDX fails to load it and complains about missing assets e.g.: 

> Caused by: com.badlogic.gdx.utils.GdxRuntimeException: No NinePatch, TextureRegion, or Texture registered with name: button.9
> 	at com.badlogic.gdx.scenes.scene2d.ui.Skin.getPatch(Skin.java:250)
> 	at com.badlogic.gdx.scenes.scene2d.ui.Skin.get(Skin.java:150)
> 	at com.badlogic.gdx.scenes.scene2d.ui.Skin$1.readValue(Skin.java:427)
> 	at com.badlogic.gdx.utils.Json.readFields(Json.java:814)
> 	... 26 more
> 

If, however, I export exactly the same skin using ver. 28 then it works without problem. The generated atlas files are the same. The only difference is in the exported json files - which I have attached. It seems to be getting upset about files with a .9 extension.

 In order to get around githubs restrictions I have added a .txt extension to each file. I have also added the version number to the file name which, obviously, will need changing. I have attached the .png and atlas files for testing.

[uiskin29.json.txt](https://github.com/raeleus/skin-composer/files/3198273/uiskin29.json.txt)

[uiskin28.json.txt](https://github.com/raeleus/skin-composer/files/3198272/uiskin28.json.txt)

[uiskin.atlas.txt](https://github.com/raeleus/skin-composer/files/3198285/uiskin.atlas.txt)

![uiskin](https://user-images.githubusercontent.com/11048658/58028092-ebaaa380-7b11-11e9-996d-e49205ad9c5a.png)

**Comment by raeleus** [comment]
Sorry about that one! It's a pretty bad bug. I found a solution for it yesterday. It'll be resolved in the next update. Thanks for the detailed report!

**Comment by phunni** [comment]
Ah - glad it's resolved already!
