### ISSUE TITLE
Too much CPU and GPU usage

### ISSUE THREAD

**Issue by Spikatrix** [raeleus/skin-composer#58]
When I open Skin Composer, one of my CPU cores gets maxed out at a constant 100% usage. My GPU is also getting used too much.

**Comment by raeleus** [comment]
Thanks for pointing that out. Hopefully it's something as simple as setting Vsync on.

**Comment by raeleus** [comment]
No, I set Vsync to true. I'm going to have to do some profiling, but I'm not sure where to look for the cause. What system specs do you have? Thanks.

**Comment by Spikatrix** [comment]
Wow, you're fast. Thanks for the reply

My specs are:
Intel Core i5 7200U processor (2 cores, 4 with HyperThreading)
Nvidia Geforce 940MX 2 GB GDRR5 variant
8 GB RAM

Is there a way to view the FPS to make sure it's a constant 60?

**Comment by raeleus** [comment]
On Windows 10? I was thinking of making a test app that can show you some debug information to make sure it's not just libGDX. That will take some time though. I wonder if I have any other LWJGL3 games to test...

https://gamejolt.com/games/please-dont-go-back/398865
Please don't be alarmed by the inappropriate content in that one. I wonder if that game will also peg your GPU/CPU too.

**Comment by raeleus** [comment]
Also, the libGDX people are asking me if it's a double GPU setup. Thanks again.

**Comment by Spikatrix** [comment]
I'm on linux, not windows. Specifically on the Zorin distro with the latest updates. 

I have the Integrated Intel GPU and the dedicated Nvidia GPU. I've installed the proprietary Nvidia drivers so everything is running on my dedicated GPU.

I just tried your game and I am having the same high CPU and GPU usage.

**Comment by raeleus** [comment]
I'm sorry to say, it's a libGDX issue with the LWJGL3 backend. The best I can do is make an issue on their GitHub. The folks on Discord made it sound like this is a more prevalent issue than I've known about before.

**Comment by Spikatrix** [comment]
I see. Thanks for investigating on this.

Also, I didn't know that libGDX had a Discord server! I'll definitely join it.

**Comment by raeleus** [comment]
Yessir! We'd love to have you. https://discord.gg/gXBJPh

**Comment by Spikatrix** [comment]
Thanks!

I'm closing this issue as it's not a Skin Composer specific issue

**Comment by Spikatrix** [comment]
Not sure how, but I don't have this issue anymore.

**Comment by raeleus** [comment]
Maybe Linux updated their drivers or something.
