### ISSUE TITLE
Impossible to save on Mac

### ISSUE THREAD

**Issue by molobala** [raeleus/skin-composer#59]
Hello,
Great work for we gamers :) 

But I'm facing with an issue on my MAC (Mojave) when saving or importing a skin I'm getting this error: 
```Impossible to convert  ".skincomposer/temp" into alias type (-1700)```

Any idea about this issue ?

**Comment by raeleus** [comment]
I might have seen that before using the .app bundle version of the tool. Can you try downloading the skin-composer-mac.jar version and run with the instructions here: https://github.com/raeleus/skin-composer/wiki/Getting-Started-With-Mac#running-skin-composer-from-jar-file ? Thanks and sorry for the trouble. I might just drop the .app bundle version if that proves to be the problem.

**Comment by raeleus** [comment]
I tested it, and the JAR version seems to work fine. Please use that going forward. Thank you.
