### ISSUE TITLE
Highlight currently selected Drawable

### ISSUE THREAD

**Issue by shoeoffhead** [raeleus/skin-composer#60]
Hi,

amazing project. A small suggestion: when clicking on any of the "Drawable Style Properties" you get a list of thumbnails representing all drawables. The currenlty selected drawable for the "clicked style property" is not highlighted in any way. The user doesn't know which style is currently selected. This would make it easier selecting a new drawable, since on can compare the current and the new drawable better if one knows which is the current one.
This is not a big deal but it would kind of improve user experience.

You could for example use red textcolor for the currently selected drawable and use yellow in the background.

**Comment by raeleus** [comment]
Hey, that's a great idea. I'll try to implement that with the next version. Thanks!

**Comment by shoeoffhead** [comment]
Great that you like it. With "yellow in the background" I meant just to highlight the drawable's name (to the red textcolor does pop out more) not the entire thumbnail.

**Comment by raeleus** [comment]
This will be included in the next version. Thank you.
