### ISSUE TITLE
Add Preview "Showcase"

### ISSUE THREAD

**Issue by shoeoffhead** [raeleus/skin-composer#61]
Hi,

I think it would be a good idea to construct a showcase that displays all of the widgets supported by a skin.

Most UI toolkits have such a widget showcase (e.g. SwingSet or SWT has one).

You could use this showcase to "preview skins" better while working on them. This would give a much better overview of how the skin as a whole performs. You would open this showcase in a new window/dialog on top of the skin composer, so users could also resize this window and test the correct behavior of the skin much more efficiently.

**Comment by raeleus** [comment]
I do have a solution for this planned. It won't be added any time soon because it's a rather complex addition. Thanks for the suggestion and stay tuned!

**Comment by shoeoffhead** [comment]
Good to know. You have so many little different "showcases" prepared (you call them Example projects) for many skins already: https://ray3k.wordpress.com/artwork

I assumed you could just pick out the good parts and combine them in one big showcase you can use in skin-composer for wholesome skin previews ;)

**Comment by raeleus** [comment]
To spoil the surprise, the idea is to create a WYSIWYG editor that lets you add widgets to a preview via a control panel. From there, it would be trivial to have a convenience button that lets you add all of your existing styles to the screen.

**Comment by shoeoffhead** [comment]
Sounds amazing! This is almost a second project, where you can quickly WYSIWYG an UI and copy the source code to the clipboard or export it. :heart:

**Comment by raeleus** [comment]
That was also an idea to allow people to copy-paste the layout to their project. I have some reservations about this because people need to learn how to code Scene2D properly and not depend on me to add features, etc.

I don't have an alpha yet, sorry. I'm making a bunch of a games at the moment, but I'm close to getting back to my regular development schedule.

**Comment by shoeoffhead** [comment]
Sure. I also hate drag&drop UI design tools. Usually people spend more time figuring out the tool instead of learning how it really works.

Still, for prototyping it would be nice to also get the source code. Maybe display a warning message that people should first learn HOW to do it before using it ;)

**Comment by raeleus** [comment]
I hope Scene Composer is the answer you would be looking for as far as Skin previews go. Some documentation can be found here: https://github.com/raeleus/skin-composer/wiki/Scene-Composer

This will be included in the next version. Thanks.
