### ISSUE TITLE
Save the preview stage colors

### ISSUE THREAD

**Issue by MrStahlfelge** [raeleus/skin-composer#63]
Minor issue, but anyway: Please store in the scmp file which colors were set for the preview stage. I have a skin with only white elements on a black background, and I have to set the color I really every time to see something. 

Thanks and great work! :)

**Comment by Sashie** [comment]
either that or an option to globally have a background color(or any of those preview options)  saved when you load the app regardless of what project is loaded

**Comment by raeleus** [comment]
Good ideas guys. I'll probably have this in the next version. Thank you.

**Comment by raeleus** [comment]
This has been resolved for the next version. Thank you.
