### ISSUE TITLE
Gradle file doesn't specify repo for tenpatch

### ISSUE THREAD

**Issue by axlan** [raeleus/skin-composer#65]
Minor issue I ran into building the project. The build would fail with an error about not finding tenpatch until I added `maven { url 'https://jitpack.io/' }` to the repo list.

**Comment by raeleus** [comment]
Thanks for the reminder. I didn't notice because I'm building locally.

**Comment by raeleus** [comment]
This is resolved with version 35. The fix is in the dev branch. Thank you.
