### ISSUE TITLE
Exporting with simple names and tenpatch reflection

### ISSUE THREAD

**Issue by arnemileswinter** [raeleus/skin-composer#66]
If i export with simple names and use tenpatch, the tenpatch class is not correctly instantiable using reflection when consuming the skin. The path (com.mypackage....) is not prefixed to tenpatches when simple names is enabled.

**Comment by raeleus** [comment]
Sorry about that! I've been short on time these last few days, but I'll definitely address this in my next bug run. Thank you so much for the report!

**Comment by raeleus** [comment]
This will be resolved with the next version. Thank you.
