### ISSUE TITLE
Ever time i hit save button nothing happens

### ISSUE THREAD

**Issue by code4passion** [raeleus/skin-composer#69]
JDK version 14
os mac
Am using jar for mac : skin-composer-mac.jar

Can see following on console

20:118: execution error: Can’t make ".skincomposer/temp" into type alias. (-1700)

**Comment by raeleus** [comment]
Sorry about the trouble! What version of OSX are you running? I'll try to
resolve on my next bug run, but these mac issues are hard to work out.

**Comment by fgermane** [comment]
Hello I am facing the same issue. Have you found a fix?
Thanks in advance.

**Comment by raeleus** [comment]
I'm working on it. I'm in the middle of my bug run for the next release.

**Comment by fgermane** [comment]
Thanks a lot :-)

**Comment by fgermane** [comment]
Hi Raeleus, 
Hope you are well.
Did you have time to fix this bug on Mac OS ?

Thanks.

Fred

**Comment by raeleus** [comment]
I haven't tested on my Mac yet, but I do have a new distribution scheme
that should solve a lot of problems. I'm working on the biggest update to
Skin Composer, so I don't want to release it prematurely. Sorry for the
inconvenience.

**Comment by fgermane** [comment]
Thanks a lot for you answer. I will wait the next release. Good luck!

**Comment by raeleus** [comment]
This will be resolved with the next version. Thank you all for your continued support.
