### ISSUE TITLE
Add support for Cyrillic characters

### ISSUE THREAD

**Issue by IsmithI** [raeleus/skin-composer#70]
Thank you for creating this awesome tool, it makes UI development so much faster! But I feel lack of Cyrillic support. I'm a Ukrainian developer and want to localize my game in English and Russian. No problem with English, but in the "create Bitmap font" view I cannot paste Cyrillic characters into the "Characters" field. Currently I'm forced to use FreeTypeFont generator inside source code to generate fonts at runtime and it would be very useful if this option is available out of the box.

**Comment by raeleus** [comment]
Thank you for making this issue. The way I support such characters is the "Load from file (UTF-8)..". option:
![image](https://user-images.githubusercontent.com/12948924/78817231-b7d5a800-7987-11ea-85ac-07c600a3fa1a.png)

Please see this guide: https://github.com/raeleus/skin-composer/wiki/Creating-Bitmap-Fonts#foreign-language-characters

If this doesn't function correctly, please let me know. Thank you.

**Comment by IsmithI** [comment]
Thank you for your response, I'll definitely try this option.
