### ISSUE TITLE
SkinComposer selectBox doesn't recognize fields

### ISSUE THREAD

**Issue by jeltedeproft** [raeleus/skin-composer#78]
![image](https://user-images.githubusercontent.com/22193978/86526545-a83a0280-be95-11ea-9c17-64b9ecec93a0.png)

Even if all mandatory fields are filled in, the ui stil shows the message that all fields need to be filled in and the export does not export selectBox.

**Comment by raeleus** [comment]
Did you make sure to also fill in the required fields for List and filled in at least one field for ScrollPane?

**Comment by jeltedeproft** [comment]
my bad!, you were right. I didnt have a list and scrollpane classes correctly filled in.

**Comment by raeleus** [comment]
Thanks for following up!
