### ISSUE TITLE
Libgdx question - JAR package

### ISSUE THREAD

**Issue by levymikael** [raeleus/skin-composer#80]
Hello,

I would like to provide my client, a package that include the updated jar, 
The client would not have to download everytime the latest version jar.
What software/cmd would  you recommend ?

Thank you

**Comment by raeleus** [comment]
Are you talking about Skin Composer updates? I don't have any functionality for it I'm afraid. If you're talking about Java JAR's in general, I'm sure there are solutions out there, but it would most likely end up being an automatic download of the latest jar veraion.
