### ISSUE TITLE
Some VisTextButtonStyle Properties Pick Wrong Asset Type

### ISSUE THREAD

**Issue by ccmb2r** [raeleus/skin-composer#82]
I'm using version 37 of Skin Composer. For the VisTextButtonStyle, the properties "overFontColor" and "checkedOverFontColor" allow me to choose fonts but not colors (where the latter is intended by the style).

**Comment by raeleus** [comment]
Thanks for the heads up. I'll look into that one soon.

**Comment by ccmb2r** [comment]
I was able to solve the problem for my concrete project by manually editing the *.scmp file. I was using the VisUI template. Hope that information helps and thanks for your work!

**Comment by raeleus** [comment]
That's exactly what I needed to do. Thank you very much! This will be resolved with the next version.
