### ISSUE TITLE
.FNT file contains a reference to font .PNG, but none is exported

### ISSUE THREAD

**Issue by scpketer** [raeleus/skin-composer#83]
I'm working on a libgdx game and I want to use a bitmap font from .FNT file (I generated it by wiki instructions), however, since it refers to font .PNG which is not exported by the skin composer, it's not loading and thus crashing.

Is there any way to export font .PNG as well?

**Comment by raeleus** [comment]
It's supposed to export a PNG as well. Try exporting to an empty folder. Try a differnt font with the default settings. What OS?

**Comment by scpketer** [comment]
Linux, I've been exporting both to empty and non-empty directories already, both cases end up exporting just atlas, skin JSON and PNG and FNT, with no PNG supplied.

**Comment by raeleus** [comment]
Oh, when you export the skin, the font is embedded in the skin PNG. No separate PNG is required.

**Comment by scpketer** [comment]
FNT still refers to font PNG rather than skin PNG..?

**Comment by raeleus** [comment]
It still works. The magic of Skin loader!
