### ISSUE TITLE
crash when creating font

### ISSUE THREAD

**Issue by Grisgram** [raeleus/skin-composer#84]
java.lang.ClassCastException: class com.ray3k.skincomposer.LeadingTruncateLabel cannot be cast to class com.badlogic.gdx.scenes.scene2d.ui.TextField (com.ray3k.skincomposer.LeadingTruncateLabel and com.badlogic.gdx.scenes.scene2d.ui.TextField are in unnamed module of loader 'app')
	at com.ray3k.skincomposer.dialog.DialogBitmapFont$6.lambda$changed$0(DialogBitmapFont.java:327)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:154)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:114)
	at com.ray3k.skincomposer.desktop.DesktopLauncher.main(DesktopLauncher.java:405)

this exception happens reproducable on every try of creating a font with the attached settings.
I enter "acme_white_18_shadow" as the filename when clicking on the .fnt name box (and then the save dialog appears).
When i click on "save" at the system save-as dialog, this crash happens.

i have a screen recording so you can see what I type - unfortunately windows game bar doesn't record the system save-as dialog but you can see what I enter 

hope this helps!

[screen-video.zip](https://github.com/raeleus/skin-composer/files/5179274/screen-video.zip)
[escape-font-settings-shadow.zip](https://github.com/raeleus/skin-composer/files/5179271/escape-font-settings-shadow.zip)

**Comment by Grisgram** [comment]
I'd like to add that I now tried with other settings (no shadow, etc) -> same crash.
So, at the moment I am not able to add any new fonts through the skin composer.

**Comment by raeleus** [comment]
Strangely enough I ran into this problem myself yesterday. Sorry for the inconvenience. I'd suggest using an older version for now, but I'll have a fix soon. Thanks for the report.

**Comment by Grisgram** [comment]
you're welcome!
Thank you very much for this great tool!

**Comment by raeleus** [comment]
Sorry this took so long to resolve. I really couldn't find the time! I've been assigned a lot of different projects. This should be resolved with version 39. Thank you.
