### ISSUE TITLE
HiDPI support

### ISSUE THREAD

**Issue by Hangman** [raeleus/skin-composer#85]
I'm sorry Raeleus but you're next on my hdpi journey.
It would be cool to have HiDPI support out of the box.
IBL composer checks the resolution it is running on to achieve this.
That's also the way I used to do it, don't know if it's the best approach though.
Example: [https://github.com/mgsx-dev/gdx-gltf/commit/e54a17d4bd920d8227ee33b74cb8d132b0199986](https://github.com/mgsx-dev/gdx-gltf/commit/e54a17d4bd920d8227ee33b74cb8d132b0199986)

**Comment by raeleus** [comment]
It's always been something that's been lingering in the back of my mind, but I've never had the hardware to test it. I'll see what I can do. Thanks!

**Comment by raeleus** [comment]
link doesn't go anywhere, btw

**Comment by Hangman** [comment]
Oops sorry, link edited. I have the hardware, so if you need anything tested just DM me on discord. I'm happy to help.

**Comment by MrStahlfelge** [comment]
I can test it, too

**Comment by raeleus** [comment]
Thanks guys. I believe this issue has been resolved. I largely just copied MGSX's approach. I would appreciate a double check that it works well enough for your devices. Thanks.

**Comment by Hangman** [comment]
I missed the notification somehow, so 4 days late but with good news. It works, thank you very much raeleus.

**Comment by raeleus** [comment]
No problem. Thanks for the suggestion!
