### ISSUE TITLE
"Lorem Ipsum" plus numbers in Fonts list

### ISSUE THREAD

**Issue by Grisgram** [raeleus/skin-composer#89]
Hi ray,

it would be great, if your template text in the fonts list would also contain numbers.
See attached screenshot, I have a font with numbers only (0123456789+-% characters) for floating damage numbers on the enemies.

In the preview of the list I can't see what the font looks like, as no character of "lorem ipsum" is part of the font.

Could you change that template string to:
a. Either a substring (first x characters) of the characters of the font if the charset is not "default"
b. to something simple like "lorem ipsum 1234"

Would be great!
TY
Cheers 
![font-view](https://user-images.githubusercontent.com/19487451/102710880-d8dfee00-42b5-11eb-845c-e9ca1698a708.jpg)

**Comment by raeleus** [comment]
I will resolve this with the next version. The preview will adapt to fonts that have glyphs for only uppercase, lowercase, or numbers. Having it figure out exactly what characters are available in fonts besides that is kind of messy and I want to avoid that.

**Comment by Grisgram** [comment]
Thanks! As always - This is great news :)
Cheers!
