### ISSUE TITLE
Recent files shall show full path

### ISSUE THREAD

**Issue by Grisgram** [raeleus/skin-composer#91]
Hi again,

we decided, for simplicity, to name the main skin of our projects always "main".
Now, with several projects in the make, the recent files list looks like this:

![image](https://user-images.githubusercontent.com/19487451/104693925-ba311380-570a-11eb-8b25-eed4bdc135b1.png)

...which makes it a wild guess of which skin to open :-)

Suggestion: ProjectData.java#172 instead of 
```newFile.name = newFile.fileHandle.nameWithoutExtension();```
add it as 
```newFile.name = newFile.fileHandle.path();```
to the recent list.
I didn't look too deep into the source, maybe this is the point where to change it.

Alternatively you could simply add a tooltip to each recent file name, showing the full path. That would fit also.
Would be great if you find this useful and if you find the time to put that in!

cheers,
Gris

**Comment by raeleus** [comment]
I'm just making a note for myself here. This will be resolved with the next update. Thanks.
