### ISSUE TITLE
Capitalisation in the file name breaks MinWidth, etc

### ISSUE THREAD

**Issue by TZVK** [raeleus/skin-composer#94]
**Problem:** If the filename for a NinePatch has capitalised letters, and a MinWidth/MinHeight setting it breaks the json entry, due to naming shenanigans. 

**Reason:** Certain entries in json and atlas force a complete lower case name, while others use the capitalised form. Thus they can't find each others. 

**Solution:** I renamed all files into lower case file names. (Important to also rename the files in the _data directory, or Skin Composer crashes with a NullPointerException)
But Skin Composer probably should force coherent naming, ideally so that capitalised names are possible.

**Comment by raeleus** [comment]
This will be resolved with the next update. Thank you.
