### ISSUE TITLE
Suggestion/Enhancement: Usage count & "replace this"

### ISSUE THREAD

**Issue by Grisgram** [raeleus/skin-composer#96]
I made a little graphic to visualize the idea.

Thing is, if you use a template skin (a download from your website, my own skin from a previous project, ...) there are several elements that shall change through the entire skin.
Be it _drawables_ like Button backgrounds, radio or checkbox graphics, as well as (most likely) _Fonts_ where the skin shall "stay as it is, but with a new font" or be it the _color scheme_.

So my suggestion is, that all the "list" dialogs (Project -> drawables, fonts, colors, ...) get a new information and a new action.

Information: "usage count" - how often is this particular element used in the skin?
Action: "replace this" (see picture)

I will gladly help impementing it if you can give me a jump start where to start, an overview of how the data is managed.

If your thought is "why should I replace a color with another? I can simply edit the color":
While this is true for colors, I can even rename them, this is not true for fonts (I had to replace a font from your skin with another that supports german umlauts) and this is a trip through hell because _ALL_ styles break when you remove a font and you must click through every single style ... A replace feature would've saved me probably more time than it needs to implement this replace feature here once and for all.
And to stay generic/even through the elements, I would simply add that replace-button to each element, so the user sees this as a common task.

Cheers
Gris/Haerion

![feature_skin_composer](https://user-images.githubusercontent.com/19487451/107749675-3ffcaa80-6d1b-11eb-96f6-05d0cb353c55.png)

**Comment by raeleus** [comment]
I'll have to ponder on this after the jam. Thanks for making the detailed description and graphic!

**Comment by Grisgram** [comment]
hey raeleus, after a long time i am going through old issues and close them - thanks for our time at libgdx
